osx_image: xcode9.2
language: objective-c
xcode_workspace: SwiftUIUtilities.xcworkspace
xcode_scheme: SwiftUIUtilities
xcode_sdk: iphonesimulator11.2
before_install:
- gem install cocoapods slather xcpretty
- pod repo update

script:
- set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace SwiftUIUtilities.xcworkspace -scheme SwiftUIUtilities -destination 'platform=iOS Simulator,name=iPhone 7' CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
- pod lib lint --quick

after_success: slather